version: 2
jobs:
  build:
    working_directory: /usr/src/app
    docker:
      - image: node:7-onbuild
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: npm run build
          command: npm run build
      - store_artifacts:
          path: dist/
          destination: dist